### ISSUE TITLE
VAE training error ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by cliangyu** [acl21/init-pools-dal#9]
======== TRAINING ========
Training Epoch: 1/200	Train Loss: 2.1762	Val Accuracy: 0.0
Traceback (most recent call last):
  File "/home/students/dipe051-1/workspace/code/init-pools-dal/tools/al/train_al.py", line 591, in <module>
    main(cfg)
  File "/home/students/dipe051-1/workspace/code/init-pools-dal/tools/al/train_al.py", line 214, in main
    best_val_acc, best_val_epoch, checkpoint_file = train_model(lSet_loader, valSet_loader, model, optimizer, cfg)
  File "/home/students/dipe051-1/workspace/code/init-pools-dal/tools/al/train_al.py", line 309, in train_model
    val_set_err = test_epoch(val_loader, model, val_meter, cur_epoch)
  File "/home/students/dipe051-1/anaconda3/envs/al-ssl-3/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/students/dipe051-1/workspace/code/init-pools-dal/tools/al/train_al.py", line 534, in test_epoch
    test_meter.log_epoch_stats(cur_epoch)
  File "/home/students/dipe051-1/workspace/code/init-pools-dal/pycls/utils/meters.py", line 266, in log_epoch_stats
    stats = self.get_epoch_stats(cur_epoch)
  File "/home/students/dipe051-1/workspace/code/init-pools-dal/pycls/utils/meters.py", line 254, in get_epoch_stats
    top1_err = self.num_top1_mis / self.num_samples
ZeroDivisionError: division by zero

**Comment by cliangyu** [comment]
Solved.
The error is in the VAE loss generation notebook.
